[project]
name = "sports-calendar"
version = "0.1.0"
description = "Manage sports event DB and calendar."
authors = [
    {name = "JolanDUBOIS",email = "jolan11.dubois@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"

dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "icalendar (>=6.3.2,<7.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "beautifulsoup4 (>=4.14.3,<5.0.0)",
    "cloudscraper (>=1.2.71,<2.0.0)",
    "google-api-python-client (>=2.187.0,<3.0.0)",
    "google-auth-httplib2 (>=0.3.0,<0.4.0)",
    "google-auth-oauthlib (>=1.2.3,<2.0.0)",
    "ics (>=0.7.2,<0.8.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "sqlalchemy (>=2.0.45,<3.0.0)",
    "rapidfuzz (>=3.14.3,<4.0.0)",
    "typer (>=0.20.0,<0.21.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "cattrs (>=25.3.0,<26.0.0)",
    "python-json-logger (>=4.0.0,<5.0.0)",
    "platformdirs (>=4.5.1,<5.0.0)",
    "itsdangerous (>=2.2.0,<3.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "sport-index",
    "nicegui>=3.10.0",
    "num2words>=0.5.14",
]

[project.scripts]
sports-calendar = "sports_calendar.__main__:app"

[tool.hatch.build.targets.wheel]
packages = ["src/sports_calendar"]

[tool.uv.sources]
sport-index = { path = "../sport-index", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2,<10.0.0",
    "ipykernel (>=7.1.0,<8.0.0)",
    "pytest-recording (>=0.13.4,<0.14.0)",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 88 

[tool.ruff.lint]
select = [
    "F", "E", "W", "B", "UP", "I", "FA", "C4", "SIM", 
    "RET", "RSE", "PIE", "N", "PTH", "TC", "S", "BLE"
]

ignore = ["D", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]