items:
- filters:
  - filter_type: teams
    name: ''
    rule: any
    sport: football
    team_ids:
    - 160
    uid: cd4bcc44
  name: ''
  sport: football
  uid: 7dc859c6
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 2
    uid: 17940a4c
  - competition_ids:
    - 775
    filter_type: competitions
    name: ''
    sport: football
    uid: 163421ec
  name: ''
  sport: football
  uid: 56965e38
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: 93d19e02
  - competition_ids:
    - 776
    filter_type: competitions
    name: ''
    sport: football
    uid: 0c8ec3d7
  name: ''
  sport: football
  uid: aa1ac3f6
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 14
    uid: 7fb3d51c
  - competition_ids:
    - 20296
    filter_type: competitions
    name: ''
    sport: football
    uid: 675dea16
  name: ''
  sport: football
  uid: 04033cd8
- filters:
  - competition_ids:
    - 5462
    filter_type: competitions
    name: ''
    sport: football
    uid: 7792b92d
  name: ''
  sport: football
  uid: 71353df9
- filters:
  - competition_ids:
    - 710
    filter_type: min_ranking
    name: ''
    ranking: 5
    reference_team: null
    rule: both
    sport: football
    uid: cd1201ef
  name: ''
  sport: football
  uid: 51062b46
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: afb65084
  - competition_ids:
    - 3952
    filter_type: competitions
    name: ''
    sport: football
    uid: 0becf56f
  name: ''
  sport: football
  uid: fb1de785
- filters:
  - competition_ids:
    - 8357
    filter_type: competitions
    name: ''
    sport: football
    uid: 3a7af840
  name: ''
  sport: football
  uid: ec82e4dc
- filters:
  - competition_ids:
    - 700
    filter_type: min_ranking
    name: ''
    ranking: 5
    reference_team: null
    rule: both
    sport: football
    uid: 9dbc3725
  name: ''
  sport: football
  uid: 8eef9ec7
- filters:
  - filter_type: teams
    name: ''
    rule: both
    sport: football
    team_ids:
    - 382
    - 360
    - 359
    - 363
    - 364
    - 367
    uid: 82eed634
  name: ''
  sport: football
  uid: 81afe16b
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: b799db14
  - competition_ids:
    - 3918
    filter_type: competitions
    name: ''
    sport: football
    uid: dc97a02c
  name: ''
  sport: football
  uid: cd2caac2
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: 61e83e76
  - competition_ids:
    - 3920
    filter_type: competitions
    name: ''
    sport: football
    uid: 4c2ecb1c
  name: ''
  sport: football
  uid: e4707fbe
- filters:
  - competition_ids:
    - 5329
    filter_type: competitions
    name: ''
    sport: football
    uid: 57bbbc44
  name: ''
  sport: football
  uid: 7dc53c3d
- filters:
  - competition_ids:
    - 740
    filter_type: min_ranking
    name: ''
    ranking: 5
    reference_team: null
    rule: both
    sport: football
    uid: 12a3afba
  name: ''
  sport: football
  uid: 06e15912
- filters:
  - filter_type: teams
    name: ''
    rule: both
    sport: football
    team_ids:
    - 86
    - 83
    - 1068
    uid: b41c6fcc
  name: ''
  sport: football
  uid: d03bb0da
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: f35091a0
  - competition_ids:
    - 3951
    filter_type: competitions
    name: ''
    sport: football
    uid: 7b5eb45c
  name: ''
  sport: football
  uid: 7364d7cf
- filters:
  - filter_type: teams
    name: ''
    rule: both
    sport: football
    team_ids:
    - 86
    - 83
    - 1068
    uid: 95b214bb
  - competition_ids:
    - 3951
    filter_type: competitions
    name: ''
    sport: football
    uid: 7d4d1420
  name: ''
  sport: football
  uid: 19e45099
- filters:
  - competition_ids:
    - 8102
    filter_type: competitions
    name: ''
    sport: football
    uid: c3560d13
  name: ''
  sport: football
  uid: 1d5e066c
- filters:
  - competition_ids:
    - 730
    filter_type: min_ranking
    name: ''
    ranking: 3
    reference_team: null
    rule: both
    sport: football
    uid: 6074577a
  name: ''
  sport: football
  uid: d1559bc2
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: 75ac999a
  - competition_ids:
    - 3956
    filter_type: competitions
    name: ''
    sport: football
    uid: 17fa0749
  name: ''
  sport: football
  uid: 50cd03e7
- filters:
  - competition_ids:
    - 8103
    filter_type: competitions
    name: ''
    sport: football
    uid: 2454ed21
  name: ''
  sport: football
  uid: 07f86073
- filters:
  - competition_ids:
    - 720
    filter_type: min_ranking
    name: ''
    ranking: 3
    reference_team: null
    rule: both
    sport: football
    uid: f30e921b
  name: ''
  sport: football
  uid: 7dff53d0
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 14
    uid: c8a15fcf
  - competition_ids:
    - 3954
    filter_type: competitions
    name: ''
    sport: football
    uid: f41b020f
  name: ''
  sport: football
  uid: 53a1bb43
- filters:
  - competition_ids:
    - 8101
    filter_type: competitions
    name: ''
    sport: football
    uid: a356e962
  name: ''
  sport: football
  uid: 321e33cb
- filters:
  - competition_ids:
    - 5501
    filter_type: competitions
    name: ''
    sport: football
    uid: 5e493861
  name: ''
  sport: football
  uid: 8e088406
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: e038de27
  - competition_ids:
    - 22902
    filter_type: competitions
    name: ''
    sport: football
    uid: f5bdf899
  name: ''
  sport: football
  uid: 27a43656
- filters:
  - filter_type: teams
    name: ''
    rule: any
    sport: football
    team_ids:
    - 2755
    uid: 7a8e7d83
  name: ''
  sport: football
  uid: 208a7635
- filters:
  - competition_ids:
    - 606
    filter_type: competitions
    name: ''
    sport: football
    uid: 74f4079c
  name: ''
  sport: football
  uid: 629e3571
- filters:
  - filter_type: teams
    name: ''
    rule: both
    sport: football
    team_ids:
    - 2755
    - 482
    - 164
    - 481
    - 449
    - 17641
    - 477
    uid: bf376bcd
  - competition_ids:
    - 786
    filter_type: competitions
    name: ''
    sport: football
    uid: 54348c0e
  name: ''
  sport: football
  uid: dd484fe4
- filters:
  - filter_type: teams
    name: ''
    rule: any
    sport: football
    team_ids:
    - 205
    - 202
    uid: cb33b5e2
  - competition_ids:
    - 780
    filter_type: competitions
    name: ''
    sport: football
    uid: 8bb33450
  name: ''
  sport: football
  uid: cd7e8eab
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: 2000e038
  - competition_ids:
    - 2395
    filter_type: competitions
    name: ''
    sport: football
    uid: 07026de3
  name: ''
  sport: football
  uid: 83a6df97
- filters:
  - filter_type: teams
    name: ''
    rule: both
    sport: football
    team_ids:
    - 2755
    - 482
    - 164
    - 481
    - 449
    - 17641
    - 477
    uid: 3e204fe0
  - competition_ids:
    - 2395
    filter_type: competitions
    name: ''
    sport: football
    uid: 580ac557
  name: ''
  sport: football
  uid: 4097b6c8
- filters:
  - competition_ids:
    - 781
    filter_type: competitions
    name: ''
    sport: football
    uid: 1f7ebb76
  name: ''
  sport: football
  uid: 2a1b1fa3
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 12
    uid: ae6197b7
  - filter_type: teams
    name: ''
    rule: any
    sport: football
    team_ids:
    - 11676
    uid: 00e9a82b
  - competition_ids:
    - 5693
    filter_type: competitions
    name: ''
    sport: football
    uid: 5b2f61dc
  name: ''
  sport: football
  uid: 3c54023f
- filters:
  - filter_type: teams
    name: ''
    rule: any
    sport: football
    team_ids:
    - 2755
    uid: 44c023be
  - competition_ids:
    - 795
    filter_type: competitions
    name: ''
    sport: football
    uid: e48a0fcd
  name: ''
  sport: football
  uid: 52dacc86
- filters:
  - competition_ids: []
    filter_type: stage
    name: ''
    sport: football
    stage: 14
    uid: 6c6cbaa3
  - competition_ids:
    - 19483
    filter_type: competitions
    name: ''
    sport: football
    uid: 3aaa8ecb
  name: ''
  sport: football
  uid: 2be06813
- filters:
  - filter_type: session
    name: ''
    sessions:
    - Race
    - Sprint
    sport: f1
    uid: 8d7011bd
  name: ''
  sport: f1
  uid: b8c06099
name: dev
