items:
- filters:
  - fields: {}
    filter_type: empty
    name: item-1-filter-1
    sport: football
    uid: it-001-filt-001
  - fields:
      competition_ids:
      - 1
      - 2
      - 3
      ranking: 5
      selection_rule:
        reference: null
        rule: both
    filter_type: min_ranking
    name: item-1-filter-2
    sport: football
    uid: it-001-filt-002
  - fields:
      selection_rule:
        reference: 40
        rule: opponent
      team_ids:
      - 10
      - 20
      - 30
    filter_type: teams
    name: item-1-filter-3
    sport: football
    uid: it-001-filt-003
  name: item-1
  sport: football
  uid: it-001
- filters:
  - fields:
      sessions:
      - Sprint
      - Race
    filter_type: session
    name: item-2-filter-1
    sport: football
    uid: it-002-filt-001
  name: item-2
  sport: f1
  uid: it-002
name: dev
