created_at: '2026-01-30T19:57:02'
items:
- created_at: '2026-01-30T19:57:02'
  filters:
  - created_at: '2026-01-30T19:57:02'
    fields:
      filter_type: empty
    name: item-1-filter-1
    sport_id: 1
    uid: it-001-filt-001
  - created_at: '2026-01-30T19:57:02'
    fields:
      competition_ids:
      - trnc:14
      - trnc:1358
      - trnc:68
      filter_type: min_ranking
      ranking: 5
      selection_rule:
        reference: null
        rule: both
    name: item-1-filter-2
    sport_id: 1
    uid: it-001-filt-002
  - created_at: '2026-01-30T19:57:02'
    fields:
      competitor_ids:
      - t-cpt:3288
      - t-cpt:3296
      - t-cpt:3280
      filter_type: competitors
      selection_rule:
        reference: t-cpt:80
        rule: opponent
    name: item-1-filter-3
    sport_id: 1
    uid: it-001-filt-003
  name: item-1
  sport_id: 1
  uid: it-001
  updated_at: '2026-01-30T19:57:02'
- created_at: '2026-01-30T19:57:02'
  filters:
  - created_at: '2026-01-30T19:57:02'
    fields:
      competition_id: stgc:81
      filter_type: sessions
      sessions:
      - 6
      - 10
    name: item-2-filter-1
    sport_id: 11
    uid: it-002-filt-001
  name: item-2
  sport_id: 11
  uid: it-002
  updated_at: '2026-01-30T19:57:02'
name: dev
updated_at: '2026-07-13T12:57:02'
