teams:
  similarity_table: team_similarity
  source_tables:
    - table_name: espn_teams
      id_col: team_id
    - table_name: live_soccer_teams
      id_col: team_name
    - table_name: football_data_teams
      id_col: team_id

competitions:
  similarity_table: competition_similarity
  source_tables:
    - table_name: espn_competitions
      id_col: competition_id
    - table_name: live_soccer_competitions
      id_col: competition
    - table_name: football_data_competitions
      id_col: competition_id

areas:
  similarity_table: area_similarity
  source_tables:
    - table_name: live_soccer_areas
      id_col: area
    - table_name: football_data_areas
      id_col: area_id
