teams:
  similarity_table: team_similarity
  source_entity_tables: 
    - name: espn_teams
      id_col: team_id
    - name: live_soccer_teams
      id_col: team_name
    - name: football_data_teams
      id_col: team_id

competitions:
  similarity_table: competition_similarity
  source_entity_tables: 
    - name: espn_competitions
      id_col: competition_id
    - name: live_soccer_competitions
      id_col: competition
    - name: football_data_competitions
      id_col: competition_id

areas:
  similarity_table: area_similarity
  source_entity_tables: 
    - name: football_data_areas
      id_col: area_id
    - name: live_soccer_areas
      id_col: area
