trigger: automatic

class_object: ESPNApiClient

instructions:
  - method: query_matches
    params:
      - competition_slug: uefa.champions
        date_from: !date_offset 0  # Today
        date_to: !date_offset 14  # 14d from today
      - competition_slug: uefa.europa
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.europa.conf
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.champions_qual
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.europa_qual
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.europa.conf_qual
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.nations
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.euro
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.euroq
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.world
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.caf
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.uefa
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.ofc
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.conmebol
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.afc
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.worldq.concacaf
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.cwc
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: conmebol.america
        date_from: !date_offset 0
        date_to: !date_offset 14 
      - competition_slug: fifa.olympics
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.friendly
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.weuro
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: uefa.wchampions
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.w.olympics
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fifa.wwc
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: eng.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: esp.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fra.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: ger.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: ita.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: por.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: nor.1
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: eng.fa
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: eng.league_cup
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: esp.copa_del_rey
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: ger.dfb_pokal
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: ita.coppa_italia
        date_from: !date_offset 0
        date_to: !date_offset 14
      - competition_slug: fra.coupe_de_france
        date_from: !date_offset 0
        date_to: !date_offset 14
    output_type: json
    save_file: espn_matches.json
