## Expected processor config:
# processor: JsonExtractionProcessor
# config_key: one of the keys in this file
# input_keys: single key "data"
# output_keys: /

int_football_espn_matches:
  direct_paths:
    id: id
    date: date
    name: name
    shortName: shortName
    season_year: season.year
    venue: venue.displayName
    stage: season.slug
    competition_id: leagues.0.id
    competition_name: leagues.0.name
    competition_abbreviation: leagues.0.abbreviation
    competition_midsizeName: leagues.0.midsizeName
    competition_slug: leagues.0.slug
    leg_value: competitions.0.leg.value
    leg_displayValue: competitions.0.leg.displayValue
    team_A_id: competitions.0.competitors.0.id
    team_A_homeAway: competitions.0.competitors.0.homeAway
    team_A_winner: competitions.0.competitors.0.winner
    team_A_score: competitions.0.competitors.0.score
    team_A_abbreviation: competitions.0.competitors.0.team.abbreviation
    team_A_displayName: competitions.0.competitors.0.team.displayName
    team_A_shortDisplayName: competitions.0.competitors.0.team.shortDisplayName
    team_A_name: competitions.0.competitors.0.team.name
    team_A_location: competitions.0.competitors.0.team.location
    team_A_venue_id: competitions.0.competitors.0.team.venue.id
    team_B_id: competitions.0.competitors.1.id
    team_B_homeAway: competitions.0.competitors.1.homeAway
    team_B_winner: competitions.0.competitors.1.winner
    team_B_score: competitions.0.competitors.1.score
    team_B_abbreviation: competitions.0.competitors.1.team.abbreviation
    team_B_displayName: competitions.0.competitors.1.team.displayName
    team_B_shortDisplayName: competitions.0.competitors.1.team.shortDisplayName
    team_B_name: competitions.0.competitors.1.team.name
    team_B_location: competitions.0.competitors.1.team.location
    team_B_venue_id: competitions.0.competitors.1.team.venue.id
    source: source
    source_type: source_type
    created_at: created_at

int_football_espn_standings:
  direct_paths:
    competition_id: id
    competition_name: name
    competition_abbreviation: abbreviation
    season: children.0.standings.season
    season_display_name: children.0.standings.seasonDisplayName
    source: source
    source_type: source_type
    created_at: created_at
  iterate:
    path: children.0.standings.entries
    columns:
      team_id: team.id
      team_location: team.location
      team_name: team.name
      team_abbreviation: team.abbreviation
      team_display_name: team.displayName
      team_short_display_name: team.shortDisplayName
      team_is_national: team.isNational
      played_games: stats.0.value
      lost: stats.1.value
      point_diff: stats.2.value
      points: stats.3.value
      goals_against: stats.4.value
      goals_for: stats.5.value
      draws: stats.6.value
      wins: stats.7.value
      deductions: stats.8.value
      ppg: stats.9.value
      rank: stats.10.value
      summary: stats.11.summary

int_football_espn_competitions:
  direct_paths:
    id: id
    alternate_id: alternateId
    name: name
    abbreviation: abbreviation
    short_name: shortName
    midsize_name: midsizeName
    slug: slug
    has_standings: hasStandings
    source: source
    source_type: source_type
    created_at: created_at

int_f1_espn_events:
  direct_paths:
    id: id
    date: date
    name: name
    short_name: shortName
    season_year: season.year
    circuit_id: circuit.id
    circuit_name: circuit.fullName
    circuit_city: circuit.address.city
    circuit_country: circuit.address.country
    source: source
    source_type: source_type
    created_at: created_at
  iterate:
    path: competitions
    columns:
      session_id: id
      session_date: date
      session_type_id: type.id
      session_type_abbreviation: type.abbreviation
