## Expected processor config:
# processor: RemapingProcessor
# config_key: one of the keys in this file
# input_keys: single key "data"
# output_keys: /

intermediate_football_live_soccer_matches:
  parser: LSParser
  method: parse_ls_matches
intermediate_football_live_soccer_standings:
  parser: LSParser
  method: parse_ls_standings
intermediate_football_live_soccer_competitions:
  parser: LSParser
  method: parse_ls_competitions
intermediate_football_football_ranking_fifa_ranking:
  parser: FRParser
  method: parse_fr_fifa_ranking

# The code associated needs to be tested again...