## Expected processor config:
# processor: RemapingProcessor
# config_key: one of the keys in this file
# input_keys: one key "data" and each key "using_table" in the designated config
# output_keys: /

staging_football_standings:
  - target_field: competition_id
    using_table: competitions
    match_on: alternate_id
    replace_by: id