name: build_staging
description: This workflow is responsible for orchestrating the data pipeline from the intermediate zone to the staging zone.
stage: staging

models:
  - name: football_competitions
    description: TODO
    trigger: automatic
    sources:
      - name: espn_football_competitions
        path: intermediate/football/espn_competitions.csv
    dependencies:
      - intermediate.espn_football_competitions
    output:
      name: competitions
      layer: staging
      path: staging/football/competitions.csv
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - name
    processing:
      processor: DerivationProcessor # TODO - Technically it's for intermediate but...
      source_key: espn_football_competitions
      output_key: football_competitions
      deduplicate: true # Shouldn't be necessary
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: football_teams
    description: TODO
    trigger: automatic
    sources:
      - name: espn_football_teams
        path: intermediate/football/espn_teams.csv
    dependencies:
      - intermediate.espn_football_teams
    output:
      name: football_teams
      layer: staging
      path: staging/football/teams.csv
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - name
          - abbreviation
    processing:
      processor: DerivationProcessor
      source_key: espn_football_teams
      output_key: football_teams
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: football_matches
    description: TODO
    trigger: automatic
    sources:
      - name: espn_football_matches
        path: intermediate/football/espn_matches.csv
    dependencies:
      - intermediate.espn_football_matches
    output:
      name: football_matches
      layer: staging
      path: staging/football/matches.csv
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - competition_id
          - home_team_id
          - away_team_id
    processing:
      processor: DerivationProcessor
      source_key: espn_football_matches
      output_key: football_matches
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: football_standings
    description: TODO
    trigger: automatic
    sources:
      - name: espn_football_standings
        path: intermediate/football/espn_standings.csv
      - name: espn_football_competitions
        path: intermediate/football/espn_competitions.csv
    dependencies:
      - intermediate.espn_football_standings
    output:
      name: football_standings
      layer: staging
      path: staging/football/standings.csv
      unique:
        field_sets:
          - [competition_id, team_id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - competition_id
          - team_id
          - position
    processing:
      processor: DerivationProcessor
      source_key: espn_football_standings
      output_key: football_standings
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: f1_events
    description: TODO
    trigger: automatic
    sources:
      - name: espn_f1_events
        path: intermediate/f1/espn_events.csv
    dependencies:
      - intermediate.espn_f1_events
    output:
      name: f1_events
      layer: staging
      path: staging/f1/events.csv
      unique:
        field_sets:
          - [id, session_id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - session_id
    processing:
      processor: DerivationProcessor
      source_key: espn_f1_events
      output_key: f1_events
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0
