name: build_staging
description: This workflow is responsible for orchestrating the data pipeline from the intermediate zone to the staging zone.
stage: staging

models:
  - name: competitions
    description: TODO
    trigger: automatic
    sources:
      - name: espn_competitions
        path: intermediate/espn_competitions.csv
    dependencies:
      - intermediate.espn_competitions
    output:
      name: competitions
      layer: staging
      path: staging/competitions.csv
      schema: competitions
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - name
    processing:
      processor: DerivationProcessor # TODO - Technically it's for intermediate but...
      source_key: espn_competitions
      output_key: competitions
      deduplicate: true # Shouldn't be necessary
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: teams
    description: TODO
    trigger: automatic
    sources:
      - name: espn_teams
        path: intermediate/espn_teams.csv
    dependencies:
      - intermediate.espn_teams
    output:
      name: teams
      layer: staging
      path: staging/teams.csv
      schema: teams
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - name
          - abbreviation
    processing:
      processor: DerivationProcessor
      source_key: espn_teams
      output_key: teams
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: matches
    description: TODO
    trigger: automatic
    sources:
      - name: espn_matches
        path: intermediate/espn_matches.csv
    dependencies:
      - intermediate.espn_matches
    output:
      name: matches
      layer: staging
      path: staging/matches.csv
      schema: matches
      unique:
        field_sets:
          - [id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - id
          - competition_id
          - home_team_id
          - away_team_id
    processing:
      processor: DerivationProcessor
      source_key: espn_matches
      output_key: matches
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0

  - name: standings
    description: TODO
    trigger: automatic
    sources:
      - name: espn_standings
        path: intermediate/espn_standings.csv
      - name: espn_competitions
        path: intermediate/espn_competitions.csv
    dependencies:
      - intermediate.espn_standings
    output:
      name: standings
      layer: staging
      path: staging/standings.csv
      schema: standings
      unique:
        field_sets:
          - [competition_id, team_id]
        version_col: staging_at
        keep: last
      non-nullable:
        fields:
          - competition_id
          - team_id
          - position
    processing:
      processor: DerivationProcessor
      source_key: espn_standings
      output_key: standings
      deduplicate: true
    static_fields:
      - name: staging_at
        value: !date_offset 0
