name: dev

items:
  ## CLUBS
  - entity: team
    id: 160 # PSG

  # UEFA Competitions
  - entity: competition
    id: 775 # UEFA Champions League
    filters:
      - filter_type: stage
        stage: league-stage

  - entity: competition
    id: 776 # UEFA Europa League
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 20296 # UEFA Europa Conference League
    filters:
      - filter_type: stage
        stage: Final

  - entity: competition
    id: 5462 # UEFA Super Cup

  # French Competitions
  - entity: competition
    id: 710 # Ligue 1
    filters:
      - filter_type: min_ranking
        competition_ids: [710]
        rule: both
        ranking: 5

  - entity: competition
    id: 3952 # Coupe de France
    filters:
      - filter_type: stage
        stage: Semifinals
  - entity: competition
    id: 8357 # Trophée des Champions

  # English Competitions
  - entity: competition
    id: 700 # Premier League
    filters:
      - filter_type: min_ranking
        competition_ids: [700]
        rule: both
        ranking: 5

  - entity: competition
    id: 700 # Premier League
    filters:
      - filter_type: teams
        team_ids: [382, 360, 359, 363, 364, 367] # Manchester City, Manchester United, Arsenal, Chelsea, Liverpool, Tottenham Hotspur
        rule: both

  - entity: competition
    id: 3918 # FA Cup
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 3920 # Carabao Cup
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 5329 # FA Community Shield

  # Spanish Competitions
  - entity: competition
    id: 740 # La Liga
    filters:
      - filter_type: min_ranking
        competition_ids: [740]
        rule: both
        ranking: 5

  - entity: competition
    id: 740 # La Liga
    filters:
      - filter_type: teams
        team_ids: [86, 83, 1068] # Real Madrid, FC Barcelona, Atlético Madrid
        rule: both

  - entity: competition
    id: 3951 # Copa del Rey
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 3951 # Copa del Rey
    filters:
      - filter_type: teams
        team_ids: [86, 83, 1068] # Real Madrid, FC Barcelona, Atlético Madrid
        rule: both

  - entity: competition
    id: 8102 # Supercopa de España

  # Italian Competitions
  - entity: competition
    id: 730 # Serie A
    filters:
      - filter_type: min_ranking
        competition_ids: [730]
        rule: both
        ranking: 3

  - entity: competition
    id: 3956 # Coppa Italia
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 8103 # Supercoppa Italiana

  # German Competitions
  - entity: competition
    id: 720 # Bundesliga
    filters:
      - filter_type: min_ranking
        competition_ids: [720]
        rule: both
        ranking: 3

  - entity: competition
    id: 3954 # DFB-Pokal
    filters:
      - filter_type: stage
        stage: Final

  - entity: competition
    id: 8101 # DFL-Supercup

  # FIFA Competitions
  - entity: competition
    id: 5501 # FIFA Club World Cup

  - entity: competition
    id: 22902 # FIFA Intercontinental Cup
    filters:
      - filter_type: stage
        stage: Semifinals

  ## NATIONAL SELECTIONS
  - entity: team
    id: 2755

  - entity: competition
    id: 606 # FIFA World Cup

  - entity: competition
    id: 786 # FIFA WC Qualifying (UEFA)
    filters:
      - filter_type: teams
        team_ids: [2755, 482, 164, 481, 449, 17641, 477] # France, Portugal, Spain, Germany, Netherlands, Switzerland, Croatia # TODO - Add england, italy, belgium
        rule: both

  - entity: competition
    id: 780 # Copa América
    filters:
      - filter_type: teams
        team_ids: [205, 202] # Brazil, Argentina
        rule: any

  - entity: competition
    id: 2395 # UEFA Nations League
    filters:
      - filter_type: stage
        stage: Semifinals

  - entity: competition
    id: 2395 # UEFA Nations League
    filters:
      - filter_type: teams
        team_ids: [2755, 482, 164, 481, 449, 17641, 477] # France, Portugal, Spain, Germany, Netherlands, Switzerland, Croatia # TODO - Add england, italy, belgium
        rule: both

  - entity: competition
    id: 781 # UEFA Euro

  - entity: competition
    id: 

  ## WOMEN'S
  - entity: competition
    id: 795 # Women's World Cup
    filters:
      - filter_type: teams
        team_ids: [2755] # France
        rule: any

  - entity: competition
    id: 19483 # Women's UEFA Champions League
    filters:
      - filter_type: stage
        stage: Final
