name: schemas_intermediate
stage: intermediate

models:
  - name: espn_matches
    path: intermediate/espn_matches.csv
    columns:
      - name: id
        unique: true
      - name: date
      - name: name
      - name: shortName
      - name: season_year
      - name: venue
      - name: leg_value
      - name: leg_displayValue
      - name: home_team_id
      - name: home_team_winner
      - name: home_team_score
      - name: home_team_abbreviation
      - name: home_team_displayName
      - name: home_team_shortDisplayName
      - name: home_team_name
      - name: home_team_location
      - name: home_team_venue_id
      - name: away_team_id
      - name: away_team_winner
      - name: away_team_score
      - name: away_team_abbreviation
      - name: away_team_displayName
      - name: away_team_shortDisplayName
      - name: away_team_name
      - name: away_team_location
      - name: away_team_venue_id
      - name: created_at
      - name: date_time_utc
      - name: date_time_cet
      - name: source
      - name: source_type
      - name: intermediate_at
  
  - name: espn_standings
    path: intermediate/espn_standings.csv
    columns:
      - name: competition_id
      - name: competition_name
      - name: competition_abbreviation
      - name: season
      - name: season_display_name
      - name: created_at
      - name: source
      - name: source_type
      - name: team_id
      - name: team_location
      - name: team_name
      - name: team_abbreviation
      - name: team_display_name
      - name: team_short_display_name
      - name: team_is_national
      - name: played_games
      - name: lost
      - name: point_diff
      - name: points
      - name: goals_against
      - name: goals_for
      - name: draws
      - name: wins
      - name: deductions
      - name: ppg
      - name: rank
      - name: summary

  - name: espn_teams
    path: intermediate/espn_teams.csv
    columns:
      - name: team_id
        unique: true
      - name: team_name
      - name: team_abbreviation
      - name: team_displayName
      - name: team_shortDisplayName
      - name: intermediate_at
  
  - name: espn_competitions
    path: intermediate/espn_competitions.csv
    columns:
      - name: id
        unique: true
      - name: alternate_id
      - name: name
      - name: abbreviation
      - name: short_name
      - name: midsize_name
      - name: slug
      - name: has_standings
      - name: created_at
      - name: source
      - name: source_type
      - name: intermediate_at

  # - name: football_data_matches
  #   path: intermediate/football_data_matches.csv
  #   columns:
  #     - name: area_id
  #     - name: area_name
  #     - name: area_code
  #     - name: competition_id
  #     - name: competition_name
  #     - name: competition_code
  #     - name: competition_type
  #     - name: season_id
  #     - name: season_start_date
  #     - name: season_end_date
  #     - name: season_current_matchday
  #     - name: id
  #       unique: true
  #     - name: utcDate
  #     - name: status
  #     - name: matchday
  #     - name: stage
  #     - name: homeTeam_id
  #     - name: homeTeam_name
  #     - name: homeTeam_shortName
  #     - name: homeTeam_tla
  #     - name: awayTeam_id
  #     - name: awayTeam_name
  #     - name: awayTeam_shortName
  #     - name: awayTeam_tla
  #     - name: winner
  #     - name: score_fullTime_home
  #     - name: score_fullTime_away
  #     - name: score_halfTime_home
  #     - name: score_halfTime_away
  #     - name: score_regularTime_home
  #     - name: score_regularTime_away
  #     - name: score_extraTime_home
  #     - name: score_extraTime_away
  #     - name: score_penalties_home
  #     - name: score_penalties_away
  #     - name: created_at
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: football_data_standings
  #   path: intermediate/football_data_standings.csv
  #   columns:
  #     - name: area_id
  #     - name: area_name
  #     - name: area_code
  #     - name: competition_id
  #       unique: true
  #     - name: competition_name
  #     - name: competition_code
  #     - name: competition_type
  #     - name: season_id
  #       unique: true
  #     - name: season_startDate
  #     - name: season_endDate
  #     - name: season_currentMatchday
  #     - name: season_winner
  #     - name: stage
  #     - name: type
  #     - name: group
  #     - name: position
  #     - name: team_id
  #       unique: true
  #     - name: team_name
  #     - name: team_shortName
  #     - name: team_tla
  #     - name: playedGames
  #     - name: won
  #     - name: draw
  #     - name: lost
  #     - name: points
  #     - name: goalsFor
  #     - name: goalsAgainst
  #     - name: goalDifference
  #     - name: created_at
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: football_ranking_fifa_rankings
  #   path: intermediate/football_ranking_fifa_rankings.csv
  #   columns:
  #     - name: team
  #     - name: team_name
  #     - name: team_code
  #     - name: position
  #     - name: points
  #     - name: created_at
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: live_soccer_matches
  #   path: intermediate/live_soccer_matches.csv
  #   columns:
  #     - name: title
  #     - name: match_date
  #     - name: source_time
  #     - name: source_tz_time
  #     - name: channels
  #     - name: competition_endpoint
  #     - name: created_at
  #     - name: source
  #     - name: source_type
  #     - name: home_team
  #     - name: away_team
  #     - name: home_score
  #     - name: away_score
  #     - name: won_penalty
  #     - name: is_final
  #     - name: area
  #     - name: competition
  #     - name: intermediate_at

  # - name: live_soccer_standings
  #   path: intermediate/live_soccer_standings.csv
  #   columns:
  #     - name: position
  #     - name: team_source_name
  #     - name: matches_played
  #     - name: wins
  #     - name: draws
  #     - name: losses
  #     - name: goals_for
  #     - name: goals_against
  #     - name: goal_difference
  #     - name: points
  #     - name: competition_endpoint
  #     - name: created_at
  #     - name: source
  #     - name: source_type
  #     - name: area
  #     - name: competition
  #     - name: intermediate_at

  # - name: football_data_teams
  #   path: intermediate/football_data_teams.csv
  #   columns:
  #     - name: team_id
  #       unique: true
  #     - name: team_name
  #     - name: team_shortName
  #     - name: tla
  #     - name: intermediate_at

  # - name: live_soccer_teams
  #   path: intermediate/live_soccer_teams.csv
  #   columns:
  #     - name: team_name
  #       unique: true
  #     - name: intermediate_at

  # - name: live_soccer_teams
  #   path: intermediate/live_soccer_teams.csv
  #   columns:
  #     - name: team_name
  #       unique: true
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at
  
  # - name: football_data_competitions
  #   path: intermediate/football_data_competitions.csv
  #   columns:
  #     - name: competition_id
  #       unique: true
  #     - name: competition_name
  #     - name: competition_code
  #     - name: competition_type
  #     - name: area_id
  #     - name: area_name
  #     - name: area_code
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: live_soccer_competitions
  #   path: intermediate/live_soccer_competitions.csv
  #   columns:
  #     - name: section_title
  #     - name: name
  #       unique: true
  #       nullable: false
  #     - name: region
  #     - name: confederation
  #     - name: area
  #     - name: competition
  #     - name: endpoint
  #     - name: source
  #     - name: source_type
  #     - name: created_at
  #     - name: intermediate_at

  # - name: football_data_areas
  #   path: intermediate/football_data_areas.csv
  #   columns:
  #     - name: area_id
  #       unique: true
  #     - name: area_name
  #     - name: area_code
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: live_soccer_areas
  #   path: intermediate/live_soccer_areas.csv
  #   columns:
  #     - name: area
  #       unique: true
  #     - name: source
  #     - name: source_type
  #     - name: intermediate_at

  # - name: team_similarity
  #   path: intermediate/team_similarity.csv
  #   columns:
  #     - name: id_A
  #       nullable: false
  #     - name: id_B
  #       nullable: false
  #     - name: source_A
  #       nullable: false
  #     - name: source_B
  #       nullable: false
  #     - name: similarity_score
  #       nullable: false
  #     - name: intermediate_at

  # - name: competition_similarity
  #   path: intermediate/competition_similarity.csv
  #   columns:
  #     - name: id_A
  #       nullable: false
  #     - name: id_B
  #       nullable: false
  #     - name: source_A
  #       nullable: false
  #     - name: source_B
  #       nullable: false
  #     - name: similarity_score
  #       nullable: false
  #     - name: intermediate_at

  # - name: area_similarity
  #   path: intermediate/area_similarity.csv
  #   columns:
  #     - name: id_A
  #       nullable: false
  #     - name: id_B
  #       nullable: false
  #     - name: source_A
  #       nullable: false
  #     - name: source_B
  #       nullable: false
  #     - name: similarity_score
  #       nullable: false
  #     - name: intermediate_at

  # - name: team_mapping
  #   path: intermediate/team_mapping.csv
  #   columns:
  #     - name: id
  #       nullable: false
  #     - name: source_id
  #       nullable: false
  #     - name: source
  #       nullable: false
  #     - name: intermediate_at

  # - name: competition_mapping
  #   path: intermediate/competition_mapping.csv
  #   columns:
  #     - name: id
  #       nullable: false
  #     - name: source_id
  #       nullable: false
  #     - name: source
  #       nullable: false
  #     - name: intermediate_at

  # - name: area_mapping
  #   path: intermediate/area_mapping.csv
  #   columns:
  #     - name: id
  #       nullable: false
  #     - name: source_id
  #       nullable: false
  #     - name: source
  #       nullable: false
  #     - name: intermediate_at

  # - name: team_registry
  #   path: intermediate/team_registry.csv
  #   columns:
  #     - name: id
  #       unique: true
  #       nullable: false
  #     - name: name
  #       nullable: false
  #     - name: short_name
  #     - name: tla
  #     - name: intermediate_at

  # - name: competition_registry
  #   path: intermediate/competition_registry.csv
  #   columns:
  #     - name: id
  #       unique: true
  #       nullable: false
  #     - name: name
  #       nullable: false
  #     - name: code
  #     - name: intermediate_at

  # - name: area_registry
  #   path: intermediate/area_registry.csv
  #   columns:
  #     - name: id
  #       unique: true
  #       nullable: false
  #     - name: name
  #       nullable: false
  #     - name: code
  #     - name: intermediate_at
