selection:
  file_path: data/selections/selection.json

google:
  credentials_file_path: credentials/client_secret.json

database:
  url: sqlite:///data/football.db

db: # tempory, will be renamed to database
  path: data/repository