selection:
  file_path: data/selections/selection.json

google:
  credentials_file_path: credentials/client_secret.json

database:
  url: sqlite:///data/football.db

repository:
  path: data/repository

selections:
  path: data/selections
