trigger: manual

class_object: FootballDataApiClient

instructions:
- method: query_areas
  output_type: json
  save_file: football_data_areas.json

- method: query_teams
  params: 
    - competition_id: 2013
    - competition_id: 2016
    - competition_id: 2021
    - competition_id: 2001
    - competition_id: 2018
    - competition_id: 2015
    - competition_id: 2002
    - competition_id: 2019
    - competition_id: 2003
    - competition_id: 2017
    - competition_id: 2152
    - competition_id: 2014
    - competition_id: 2000
  output_type: json
  save_file: football_data_teams.json