trigger: automatic

class_object: LiveSoccerScraper

instructions:
- method: scrape_matches
  params: 
    - competition_endpoint: /france/ligue-1
    - competition_endpoint: /france/coupe-de-france
    - competition_endpoint: /france/super-cup
    - competition_endpoint: /england/premier-league
    - competition_endpoint: /england/fa-cup
    - competition_endpoint: /england/league-cup
    - competition_endpoint: /england/fa-community-shield
    - competition_endpoint: /italy/serie-a
    - competition_endpoint: /italy/coppa-italia
    - competition_endpoint: /italy/supercoppa-italiana
    - competition_endpoint: /spain/primera-division
    - competition_endpoint: /spain/copa-del-rey
    - competition_endpoint: /spain/spanish-super-cup
    - competition_endpoint: /germany/bundesliga
    - competition_endpoint: /germany/german-cup
    - competition_endpoint: /germany/dfl-supercup
    - competition_endpoint: /international/uefa-champions-league
    - competition_endpoint: /international/uefa-europa-league
    - competition_endpoint: /international/uefa-europa-conference-league
    - competition_endpoint: /international/uefa-super-cup
    - competition_endpoint: /international/fifa-club-world-cup
    - competition_endpoint: /international/uefa-european-championship
    - competition_endpoint: /international/uefa-euro-qualifying
    - competition_endpoint: /international/uefa-nations-league
    - competition_endpoint: /international/world-cup
    - competition_endpoint: /international/copa-america
    - competition_endpoint: /international/africa-cup-of-nations
  output_type: csv
  save_file: live_soccer_matches.csv

- method: scrape_standings
  params: 
    - competition_endpoint: /france/ligue-1
    - competition_endpoint: /england/premier-league
    - competition_endpoint: /italy/serie-a
    - competition_endpoint: /spain/primera-division
    - competition_endpoint: /germany/bundesliga
  output_type: csv
  save_file: live_soccer_standings.csv