defaults:
  date_range: &date_range
    date_from: !date_offset 0
    date_to: !date_offset 14

name: dev_build_landing
description: Ingests data to the landing layer from the different sources (API and Scrapers).
stage: landing

models:
  - name: landing_football_espn_matches
    description: Ingests match information from the ESPN API.
    trigger: automatic

    output:
      name: landing_football_espn_matches
      layer: landing
      path: landing/football/espn_matches.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_espn_matches
          output_key: landing_football_espn_matches
        params:
          - sport: soccer
            league: uefa.champions
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.europa
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.europa.conf
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.champions_qual
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.europa_qual
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.europa.conf_qual
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.nations
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.euro
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.euroq
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.world
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.caf
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.uefa
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.ofc
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.conmebol
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.afc
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.worldq.concacaf
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.cwc
            <<: *date_range
            trim: true
          - sport: soccer
            league: conmebol.america
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.olympics
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.friendly
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.weuro
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.wchampions
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.w.olympics
            <<: *date_range
            trim: true
          - sport: soccer
            league: fifa.wwc
            <<: *date_range
            trim: true
          - sport: soccer
            league: eng.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: esp.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: fra.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: ger.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: ita.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: por.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: nor.1
            <<: *date_range
            trim: true
          - sport: soccer
            league: eng.fa
            <<: *date_range
            trim: true
          - sport: soccer
            league: eng.league_cup
            <<: *date_range
            trim: true
          - sport: soccer
            league: esp.copa_del_rey
            <<: *date_range
            trim: true
          - sport: soccer
            league: ger.dfb_pokal
            <<: *date_range
            trim: true
          - sport: soccer
            league: ita.coppa_italia
            <<: *date_range
            trim: true
          - sport: soccer
            league: fra.coupe_de_france
            <<: *date_range
            trim: true
          - sport: soccer
            league: uefa.euro_u21
            <<: *date_range
            trim: true

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: espn
      - name: source_type
        value: api

  - name: landing_football_espn_standings
    description: Ingests standings information from the ESPN API.
    trigger: automatic

    output:
      name: landing_football_espn_standings
      layer: landing
      path: landing/football/espn_standings.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_espn_standings
          output_key: landing_football_espn_standings
        params:
          - sport: soccer
            league: uefa.champions
            trim: true
          - sport: soccer
            league: uefa.europa
            trim: true
          - sport: soccer
            league: uefa.europa.conf
            trim: true
          - sport: soccer
            league: uefa.champions_qual
            trim: true
          - sport: soccer
            league: uefa.europa_qual
            trim: true
          - sport: soccer
            league: uefa.europa.conf_qual
            trim: true
          - sport: soccer
            league: uefa.nations
            trim: true
          - sport: soccer
            league: uefa.euro
            trim: true
          - sport: soccer
            league: uefa.euroq
            trim: true
          - sport: soccer
            league: fifa.world
            trim: true
          - sport: soccer
            league: fifa.worldq.caf
            trim: true
          - sport: soccer
            league: fifa.worldq.uefa
            trim: true
          - sport: soccer
            league: fifa.worldq.ofc
            trim: true
          - sport: soccer
            league: fifa.worldq.conmebol
            trim: true
          - sport: soccer
            league: fifa.worldq.afc
            trim: true
          - sport: soccer
            league: fifa.worldq.concacaf
            trim: true
          - sport: soccer
            league: fifa.cwc
            trim: true
          - sport: soccer
            league: conmebol.america
            trim: true
          - sport: soccer
            league: fifa.olympics
            trim: true
          - sport: soccer
            league: fifa.friendly
            trim: true
          - sport: soccer
            league: uefa.weuro
            trim: true
          - sport: soccer
            league: uefa.wchampions
            trim: true
          - sport: soccer
            league: fifa.w.olympics
            trim: true
          - sport: soccer
            league: fifa.wwc
            trim: true
          - sport: soccer
            league: eng.1
            trim: true
          - sport: soccer
            league: esp.1
            trim: true
          - sport: soccer
            league: fra.1
            trim: true
          - sport: soccer
            league: ger.1
            trim: true
          - sport: soccer
            league: ita.1
            trim: true
          - sport: soccer
            league: por.1
            trim: true
          - sport: soccer
            league: nor.1
            trim: true
          - sport: soccer
            league: eng.fa
            trim: true
          - sport: soccer
            league: eng.league_cup
            trim: true
          - sport: soccer
            league: esp.copa_del_rey
            trim: true
          - sport: soccer
            league: ger.dfb_pokal
            trim: true
          - sport: soccer
            league: ita.coppa_italia
            trim: true
          - sport: soccer
            league: fra.coupe_de_france
            trim: true
          - sport: soccer
            league: uefa.euro_u21
            trim: true

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: espn
      - name: source_type
        value: api

  - name: landing_football_espn_competitions
    description: Ingests competition information from the ESPN API.
    trigger: manual

    output:
      name: landing_football_espn_competitions
      layer: landing
      path: landing/football/espn_competitions.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_espn_competitions
          output_key: landing_football_espn_competitions
        params:
          - sport: soccer
            trim: true

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: espn
      - name: source_type
        value: api

  - name: landing_f1_espn_events
    description: Ingests F1 event information from the ESPN API.
    trigger: automatic

    output:
      name: landing_f1_espn_events
      layer: landing
      path: landing/f1/espn_events.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_f1_espn_events
          output_key: landing_f1_espn_events
        params:
          - sport: racing
            league: f1
            date_from: !date_offset 0
            date_to: !date_offset 90
            trim: true

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: espn
      - name: source_type
        value: api

  - name: landing_football_football_data_matches
    description: Ingests match information from the Football Data API.
    trigger: automatic

    output:
      name: landing_football_football_data_matches
      layer: landing
      path: landing/football/football_data_matches.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_football_data_matches
          output_key: landing_football_football_data_matches
        params:
          - competition_id: 2013
            <<: *date_range
          - competition_id: 2016
            <<: *date_range
          - competition_id: 2021
            <<: *date_range
          - competition_id: 2001
            <<: *date_range
          - competition_id: 2018
            <<: *date_range
          - competition_id: 2015
            <<: *date_range
          - competition_id: 2002
            <<: *date_range
          - competition_id: 2019
            <<: *date_range
          - competition_id: 2003
            <<: *date_range
          - competition_id: 2017
            <<: *date_range
          - competition_id: 2152
            <<: *date_range
          - competition_id: 2014
            <<: *date_range
          - competition_id: 2000
            <<: *date_range

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: football_data
      - name: source_type
        value: api

  - name: landing_football_football_data_standings
    description: Ingests standings information from the Football Data API.
    trigger: automatic

    output:
      name: landing_football_football_data_standings
      layer: landing
      path: landing/football/football_data_standings.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_football_data_standings
          output_key: landing_football_football_data_standings
        params:
          - competition_id: 2013
          - competition_id: 2016
          - competition_id: 2021
          - competition_id: 2015
          - competition_id: 2002
          - competition_id: 2019
          - competition_id: 2003
          - competition_id: 2017
          - competition_id: 2014

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: football-data
      - name: source_type
        value: api

  - name: landing_football_football_data_teams
    description: Ingests team information from the Football Data API.
    trigger: manual

    output:
      name: landing_football_football_data_teams
      layer: landing
      path: landing/football/football_data_teams.json
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_football_data_teams
          output_key: landing_football_football_data_teams
        params:
          - competition_id: 2013
          - competition_id: 2016
          - competition_id: 2021
          - competition_id: 2001
          - competition_id: 2018
          - competition_id: 2015
          - competition_id: 2002
          - competition_id: 2019
          - competition_id: 2003
          - competition_id: 2017
          - competition_id: 2152
          - competition_id: 2014
          - competition_id: 2000

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: football-data
      - name: source_type
        value: api

  - name: landing_football_live_soccer_matches
    description: Ingests match information from the Live Soccer Scraper.
    trigger: automatic

    output:
      name: landing_football_live_soccer_matches
      layer: landing
      path: landing/football/live_soccer_matches.csv
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_live_soccer_matches
          output_key: landing_football_live_soccer_matches
        params:
          - competition_endpoint: /france/ligue-1
          - competition_endpoint: /france/coupe-de-france
          - competition_endpoint: /france/super-cup
          - competition_endpoint: /england/premier-league
          - competition_endpoint: /england/fa-cup
          - competition_endpoint: /england/league-cup
          - competition_endpoint: /england/fa-community-shield
          - competition_endpoint: /italy/serie-a
          - competition_endpoint: /italy/coppa-italia
          - competition_endpoint: /italy/supercoppa-italiana
          - competition_endpoint: /spain/primera-division
          - competition_endpoint: /spain/copa-del-rey
          - competition_endpoint: /spain/spanish-super-cup
          - competition_endpoint: /germany/bundesliga
          - competition_endpoint: /germany/german-cup
          - competition_endpoint: /germany/dfl-supercup
          - competition_endpoint: /international/uefa-champions-league
          - competition_endpoint: /international/uefa-europa-league
          - competition_endpoint: /international/uefa-europa-conference-league
          - competition_endpoint: /international/uefa-super-cup
          - competition_endpoint: /international/fifa-club-world-cup
          - competition_endpoint: /international/uefa-european-championship
          - competition_endpoint: /international/uefa-euro-qualifying
          - competition_endpoint: /international/uefa-nations-league
          - competition_endpoint: /international/world-cup
          - competition_endpoint: /international/copa-america
          - competition_endpoint: /international/africa-cup-of-nations

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: live_soccer
      - name: source_type
        value: scraper

  - name: landing_football_live_soccer_standings
    description: Ingests live standings information from the Live Soccer Scraper.
    trigger: automatic

    output:
      name: landing_football_live_soccer_standings
      layer: landing
      path: landing/football/live_soccer_standings.csv
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_live_soccer_standings
          output_key: landing_football_live_soccer_standings
        params:
          - competition_endpoint: /france/ligue-1
          - competition_endpoint: /england/premier-league
          - competition_endpoint: /italy/serie-a
          - competition_endpoint: /spain/primera-division
          - competition_endpoint: /germany/bundesliga

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: livesoccertv
      - name: source_type
        value: scraper

  - name: landing_football_live_soccer_competitions
    description: Ingests live competition information from the Live Soccer Scraper.
    trigger: manual

    output:
      name: landing_football_live_soccer_competitions
      layer: landing
      path: landing/football/live_soccer_competitions.csv
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_live_soccer_competitions
          output_key: landing_football_live_soccer_competitions

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: livesoccertv
      - name: source_type
        value: scraper

  - name: landing_football_football_ranking_fifa_rankings
    description: Ingests FIFA rankings from the Football Ranking Scraper.
    trigger: automatic

    output:
      name: landing_football_football_ranking_fifa_rankings
      layer: landing
      path: landing/football/football_ranking_fifa_rankings.csv
      mode: append

    processing:
      - processor: ClientProcessor
        io_info:
          config_key: landing_football_football_ranking_fifa_rankings
          output_key: landing_football_football_ranking_fifa_rankings

    static_fields:
      - name: created_at
        value: !date_offset 0
      - name: source
        value: football-ranking
      - name: source_type
        value: scraper
