version: 1


formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%H:%M:%S"

  detailed:
    format: "%(asctime)s [%(levelname)s] [%(name)s] [%(filename)s:%(lineno)d] (%(funcName)s) - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file_debug_handler:
    class: logging.FileHandler
    filename: "__LOG_FILE__"
    level: DEBUG
    formatter: detailed

loggers:
  sports_calendar:
    level: DEBUG

  # Application loggers
  sports_calendar.application:
    level: DEBUG

  sports_calendar.application.selection:
    level: DEBUG

  sports_calendar.application.workflows:
    level: DEBUG

  # Core loggers
  sports_calendar.core:
    level: DEBUG

  sports_calendar.core.calendar:
    level: DEBUG

  sports_calendar.core.selection:
    level: DEBUG

  sports_calendar.core.utils:
    level: DEBUG

  # Infrastructure loggers
  sports_calendar.infra:
    level: DEBUG

  sports_calendar.infra.config:
    level: DEBUG

  sports_calendar.infra.engine:
    level: DEBUG

  sports_calendar.infra.engine.executors:
    level: DEBUG

  sports_calendar.infra.google_calendar:
    level: DEBUG

  sports_calendar.infra.setup:
    level: DEBUG

  sports_calendar.infra.storage:
    level: DEBUG

  # Interfaces loggers
  sports_calendar.interfaces:
    level: DEBUG

  sports_calendar.interfaces.cli:
    level: DEBUG

  sports_calendar.interfaces.gui:
    level: DEBUG

  sports_calendar.interfaces.gui.components:
    level: DEBUG

  sports_calendar.interfaces.gui.pages:
    level: DEBUG

  # Third party loggers
  googleapiclient.discovery_cache:
    level: DEBUG
    handlers: [file_debug_handler]
    propagate: False

  urllib3:
    level: WARNING
    handlers: []
    propagate: False

  # TODO - Setup sport-index logger

root:
  level: DEBUG
  handlers: [console_handler, file_debug_handler]
  propagate: False
