

# Exemple of admin overrides for entity resolution
rules:
  - type: force_match
    entity_type: team
    entities:
      - source: espn
        source_id: ...
      - source: football-data
        source_id: 524
      - source: livesoccertv
        source_id: ...

  - type: block_match
    entity_type: competition
    entities:
      - source: espn
        source_id: 775
      - source: football-data
        source_id: ...

  # - type: force_canonical
  #   entity_type: area
  #   entity:
  #     source: livesoccertv
  #     table: live_soccer_areas
  #     field: area
  #     value: france
  #   forced_canonical_value: France

  # - type: alias_merge
  #   entity_type: ...
  #   table:
  #     source: ...
  #     table: ...
  #   records: 
  #     - field: ...
  #       value: ...
  #     - field: ...
  #       value: ...
