espn_teams:
  extraction_type: double
  columns_mapping:
    team_id: [home_team_id, away_team_id]
    team_location: [home_team_location, away_team_location]
    team_name: [home_team_name, away_team_name]
    team_abbreviation: [home_team_abbreviation, away_team_abbreviation]
    team_display_name: [home_team_displayName, away_team_displayName]
    team_short_display_name: [home_team_shortDisplayName, away_team_shortDisplayName]
    source: [source, source]
    source_type: [source_type, source_type]

# espn_teams:
#   extraction_type: simple
#   columns_mapping:
#     team_id: team_id
#     team_location: team_location
#     team_name: team_name
#     team_abbreviation: team_abbreviation
#     team_display_name: team_display_name
#     team_short_display_name: team_short_display_name
#     team_is_national: team_is_national
#     source: source
#     source_type: source_type

live_soccer_teams:
  extraction_type: double
  columns_mapping:
    team_name: [home_team, away_team]
    source: [source, source]
    source_type: [source_type, source_type]

espn_competitions:
  extraction_type: simple
  columns_mapping:
    competition_id: competition_id
    competition_name: competition_name
    competition_abbreviation: competition_abbreviation
    competition_midsizeName: competition_midsizeName
    competition_slug: competition_slug
    source: source
    source_type: source_type

football_data_competitions:
  extraction_type: simple
  columns_mapping:
    competition_id: competition_id
    competition_name: competition_name
    competition_code: competition_code
    competition_type: competition_type
    area_id: area_id
    area_name: area_name
    area_code: area_code
    source: source
    source_type: source_type

football_data_areas:
  extraction_type: simple
  columns_mapping: 
    area_id: area_id
    area_name: area_name
    area_code: area_code
    source: source
    source_type: source_type

live_soccer_areas:
  extraction_type: simple
  columns_mapping:
    area: area
    source: source
    source_type: source_type

competitions:
  extraction_type: simple
  columns_mapping:
    id: id
    # standings_id: alternate_id
    name: name
    abbreviation: abbreviation
    short_name: short_name
    has_standings: has_standings

teams:
  extraction_type: simple
  columns_mapping:
    id: team_id
    name: team_name
    abbreviation: team_abbreviation
    display_name: team_display_name
    short_display_name: team_short_display_name
    # is_national: team_is_national
    location: team_location

matches:
  extraction_type: simple
  columns_mapping:
    id: id
    competition_id: competition_id
    date_time_utc: date_time_utc
    date_time_cet: date_time_cet
    home_team_id: home_team_id
    away_team_id: away_team_id
    season_year: season_year
    stage: stage
    leg: leg_value
    leg_display: leg_displayValue
    venue: venue

standings:
  extraction_type: simple
  columns_mapping:
    competition_id: competition_id
    team_id: team_id
    position: rank
    points: points
    point_diff: point_diff
    matches_played: played_games
    wins: wins
    draws: draws
    losses: lost
    goals_for: goals_for
    goals_against: goals_against
    deductions: deductions
    ppg: ppg
